### ISSUE TITLE
On randomizing when the same hero is picked, it seems that the button did not work.

### ISSUE THREAD

**Issue by pratikyoff** [kortik0/Dota2-Random-Hero#5]
One possible solution to this would be to random from a pool not containing the hero. An edge case would be when only one hero satisfies the filters.

**Comment by kortik0** [comment]
Hi. Thanks for your feedback, I will see how can I update the interface to notify people that only 1 hero can be randomized, and in another situation prevent one of the same character from being randomized.

**Comment by kortik0** [comment]
Opened a separate branch for bug fixes and refactoring.
You can check the current fixed implementation [here](https://dota2-random-hero-git-refactoringfunctionality-kortik0.vercel.app).
If you have any other suggestions on this topic, I will be glad to see them.

**Comment by pratikyoff** [comment]
Hey, the changes look good, thanks for promptly take care of the issue.
